# Generated by Django 3.1.1 on 2020-10-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='Pending', max_length=12, verbose_name='Status fo the booking'),
        ),
    ]
