# Generated by Django 3.1.1 on 2020-09-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200922_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
