# Generated by Django 3.1.1 on 2020-09-27 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_identificationtype'),
        ('users', '0007_auto_20200926_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='identification_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.identificationtype'),
        ),
    ]
