# Generated by Django 3.1.1 on 2020-10-03 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200930_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format : +999999999. Up to 15 digits allowed.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
