# Generated by Django 3.1.1 on 2020-09-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='locations/pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='location name')),
                ('description', models.TextField(max_length=2000, verbose_name='location description')),
                ('address', models.CharField(max_length=50, verbose_name='local address')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('contact_email', models.EmailField(max_length=30, verbose_name='contact email')),
                ('price', models.FloatField(max_length=10, verbose_name='location price')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('aditional_info', models.TextField(blank=True)),
                ('latitude', models.FloatField(max_length=20, verbose_name='latitude')),
                ('longitude', models.FloatField(max_length=20, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=False, help_text='If active, can be listed for rent', verbose_name='active location')),
                ('has_parking', models.BooleanField(default=False, help_text='Location has parking space', verbose_name='parking')),
                ('has_dressing_room', models.BooleanField(default=False, help_text='Location has dressing room space', verbose_name='dressing room')),
                ('has_bathroom', models.BooleanField(default=False, help_text='Location has bathroom', verbose_name='bathroom')),
                ('has_cattering', models.BooleanField(default=False, help_text='Location has cattering space', verbose_name='cattering')),
                ('has_wifi', models.BooleanField(default=False, help_text='Location has wifi available', verbose_name='wifi')),
                ('is_verified', models.BooleanField(default=False, help_text='locations has to be verified before listed for rent', verbose_name='verified location')),
                ('categories', models.ManyToManyField(through='locations.Group', to='locations.Category')),
                ('locations_images', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='locations.image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
