# Generated by Django 3.1.1 on 2020-10-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='main_image',
            field=models.ImageField(null=True, upload_to='locations/pictures', verbose_name='Main picture of a location'),
        ),
    ]
