# Generated by Django 3.1.1 on 2020-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='locations/pictures', verbose_name='Image of a location'),
        ),
    ]
