# Generated by Django 3.1.1 on 2020-10-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201005_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=150, verbose_name='local address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='location name'),
        ),
    ]
