# Generated by Django 3.1.1 on 2020-10-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20201004_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='accesibility',
            field=models.SmallIntegerField(default=0, verbose_name='Accesibility of location'),
        ),
        migrations.AddField(
            model_name='rating',
            name='average',
            field=models.SmallIntegerField(default=0, verbose_name='value for money of the location'),
        ),
        migrations.AddField(
            model_name='rating',
            name='conditions',
            field=models.SmallIntegerField(default=0, verbose_name='Conditions of location'),
        ),
    ]
